name: Create Tables
on: [push]

jobs:
  Structure-Fred-Series:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Get date
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Creating README tables
        run: |
          echo Running File...
          status=$(python Methodology/create_tables.py > logs/create_tables/${{ env.MY_DATE }}.txt 2>&1; echo $?)
          cat logs/create_tables/${{ steps.date.outputs.today }}.txt
          echo ::set-output name=status::$status
      - name: Commit files and log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout master
          git diff-index --quiet HEAD || git commit -am "Create Tables"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"
